version: '3'
services:
  node:
    build: ./docker/node
    container_name: "blackproject-mongtype-node"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/var/www/app
    tty: true
